version: "3.9"
services:
  copilot:
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build:
      context: .
      dockerfile: docker/copilot/Dockerfile
    container_name: copilot
    restart: unless-stopped
    depends_on:
      - weaviate
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - copilot
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.19.6
    restart: on-failure
    environment:
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - /var/weaviate:/var/lib/weaviate
  frontend:
    image: ghcr.io/opencopilotdev/opencopilot-frontend:latest
    ports:
      - "3001:3001"
    environment:
      - 'BACKEND_HOST=http://nginx:80'
      - 'PORT=3001'
    command: pnpm start