name: E2E Test Release

on:
  push:
    branches: [ release-ci ]
    # Pattern matched against refs/tags
    tags:
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  e2e-test-release:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: "Set up Python 3.10"
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: "Install requirements"
        run: |
          pip install --upgrade pip
          pip install --upgrade build
      - name: "Build opencopilot-ai"
        run: |
          python -m build
      - name: "Install opencopilot-ai"
        run: |
          wheel_path=dist/$(ls dist | grep .whl)
          pip install $wheel_path
          pip install libmagic==1.0
          pip install playwright==1.37.0
          pip install beautifulsoup4
          playwright install
      - name: "Setup env"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          HELICONE_API_KEY: ${{ secrets.HELICONE_API_KEY }}
        run: |
          export OPENAI_API_KEY="$OPENAI_API_KEY"
          export HELICONE_API_KEY="$HELICONE_API_KEY"
      - name: "Start Weaviate"
        run: |
          docker run \
            -e CONTEXTIONARY_URL="contextionary:9999" \
            -e QUERY_DEFAULTS_LIMIT="25" \
            -e AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED="true" \
            -e PERSISTENCE_DATA_PATH="/var/lib/weaviate" \
            -e CLUSTER_HOSTNAME="node1" \
            -p 8080:8080 \
            -d \
            semitechnologies/weaviate:1.19.6 \
              --host 0.0.0.0 --port '8080' --scheme http
      - name: "Start Copilot"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd examples/ready_player_me_copilot
          nohup python copilot.py &> logs.log &
          sleep 30
          cat logs.log
      - name: "Ping until backend up"
        run: |
          PYTHONPATH=. python tests/assets/ping_backend.py
      - name: "Test Backend"
        run: |
          PYTHONPATH=. python tests/e2e/test_backend.py
